version: '3'

services:
  pg_db:
    image: postgres:13
    container_name: bitcoin-pg
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  


  backend:
    build: ./backend
    container_name: "backend"
    depends_on:
      - pg_db
    

  frontend:
    build: ./frontend
    container_name: "frontend"
    depends_on:
      - backend
    

  proxy:
    build: ./nginx
    container_name: "proxy"
    
    restart: always
    ports:
      - "80:80"
